version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    ignore:
      - dependency-name: "@types/node"
        versions:
          - ">=25.0.0"
      - dependency-name: "conventional-changelog-conventionalcommits"
        versions:
          - ">=10.0.0"
    schedule:
      interval: "weekly"
    groups:
      jest-updates:
        applies-to: version-updates
        patterns:
          - "jest"
          - "@types/jest"
          - "ts-jest"
        update-types:
          - "minor"
          - "patch"
          - "major"
      nodejs-regular-updates:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "jest"
          - "@types/jest"
          - "ts-jest"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-regular-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
          - "major"
