name: Auto Tagging
on:
  pull_request:
    branches:
      - main
    paths:
      - "dist/index.js"
      - "package.json"
  push:
    branches:
      - main
    paths:
      - "dist/index.js"
      - "package.json"
jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      value: ${{ steps.get_version.outputs.value }}
      tagged: ${{ steps.tagged.outputs.tagged }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
      - name: Extract version from package.json
        uses: sergeysova/jq-action@a3f0d4ff59cc1dddf023fc0b325dd75b10deec58
        id: get_version
        with:
          cmd: "jq .version package.json -r"
      - name: Debug Version
        run: echo "VERSION=${{ steps.get_version.outputs.value }}"
      - name: "Check: package version has corresponding git tag"
        id: tagged
        shell: bash
        run: |
          git show-ref --tags --verify --quiet -- "refs/tags/v${{ steps.get_version.outputs.value }}" &&
          echo "tagged=true" >> $GITHUB_OUTPUT ||
          echo "tagged=false" >> $GITHUB_OUTPUT
      - name: Debug Output
        run: echo "TAGGED=${{ steps.tagged.outputs.tagged }}"
  file:
    name: check dist/index.js have changed
    runs-on: ubuntu-latest
    needs:
      - version
    outputs:
      dist_changed: ${{ steps.file.outputs.dist_changed }}
    if: needs.version.outputs.value != '0.0.0' && needs.version.outputs.tagged == 'false'
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
      - name: Check if dist/index.js has changed
        id: file
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "dist/index.js"; then
            echo "dist/index.js has changed"
            echo "dist_changed=true" >> $GITHUB_OUTPUT
          else
            echo "dist/index.js has not changed"
            echo "dist_changed=false" >> $GITHUB_OUTPUT
            exit 1
          fi
      - name: Debug Output
        run: echo "DIST_CHANGED=${{ steps.file.outputs.dist_changed }}"
  tag:
    runs-on: ubuntu-latest
    needs:
      - version
      - file
    if: |
      github.event_name == 'push' &&
      needs.version.outputs.value != '0.0.0' &&
      needs.version.outputs.tagged == 'false' &&
      needs.file.outputs.dist_changed == 'true'
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Push tag
        id: tag_version
        uses: reflective-technology/github-tag-action@c3da065c3412e17e29e9f66c7a08ce8e41aaa1df
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          custom_tag: ${{ needs.version.outputs.value }}
      - uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd
        with:
          makeLatest: ${{ !contains(needs.version.outputs.value, 'rc') }}
          prerelease: ${{ contains(needs.version.outputs.value, 'rc') }}
          generateReleaseNotes: true
          skipIfReleaseExists: true
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
