name: "Reviewdog"
on:
  pull_request:
    branches: ["main"]
permissions:
  contents: read
  pull-requests: write
jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Run detect-secrets
        uses: reviewdog/action-detect-secrets@964728f040a48396239d7fbe5e2746f7209df406
        with:
          reporter: "github-pr-review"
          detect_secrets_flags: |
            --exclude-files 'dist/*'
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: "package.json"
      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@$(node -p "require('./package.json').packageManager.split('@')[1]") --activate
      - name: Enable Yarn cache
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: "package.json"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Run ESLint
        uses: reviewdog/action-eslint@556a3fdaf8b4201d4d74d406013386aa4f7dab96
        with:
          reporter: "github-pr-review"
