name: "Test"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: package.json
      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@$(node -p "require('./package.json').packageManager.split('@')[1]") --activate
      - name: Enable Yarn cache
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: "package.json"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run tests
        run: yarn test
      - name: Lint Check
        run: yarn check
      - name: Build
        run: yarn build
